--- 
- hosts: localhost
  connection: local
  become: true

  tasks:
  - name: install packages
    package: 
      name: 
        - htop
        - vim
        - neovim
        - firefox
        - tmux
        - python-psutil
        - fish
        - go
        - telegram-desktop
  
  -name: Copy ssh keys
    copy: 
      src: files/wallpaper.jpg
      dest: /usr/share/backgrounds/gnome/ansible-wallpaper.jpg
      owner: domain80
      group: domain80


  - name: copy wallpaper file
    copy: 
      src: files/wallpaper.jpg
      dest: /usr/share/backgrounds/gnome/ansible-wallpaper.jpg
      owner: root
      group: root

  - name: setup wallpaper
    become_user: domain80
    dconf: 
      key: "/org/gnome/desktop/background/picture-uri"
      value: "'file:///usr/share/backgrounds/gnome/ansible-wallpaper.jpg'"

  - name: setup dark mode wallpaper
    become_user: domain80
    dconf: 
      key: "/org/gnome/desktop/background/picture-uri-dark"
      value: "'file:///usr/share/backgrounds/gnome/ansible-wallpaper.jpg'"

  - name: setup wallpaper position
    become_user: domain80
    dconf: 
      key: "/org/gnome/desktop/background/picture-options"
      value: "'zoom'"

  - name: remove application switcher shortcut
    become_user: domain80
    dconf: 
      key: "/org/gnome/desktop/wm/keybindings/switch-applications"
      value: "@as []"


  - name: set windows switcher shortcut
    become_user: domain80
    dconf: 
      key: "/org/gnome/desktop/wm/keybindings/switch-windows"
      value: "['<Super>Tab', '<Alt>Tab']"



